url = "https://github.com/nakajima/hyperlinked/releases/download/v0.1.3/hyperlinked-0.1.3-x86_64-unknown-linux-gnu.tar.gz"
start = "./hyperlinked serve"
app = "hyperlinked"
apt_packages = [
    "chromium-browser",
    "fontconfig",
    "fonts-noto",
    "fonts-noto-cjk",
    "fonts-noto-color-emoji",
]
required_env = [
    "DATABASE_URL",
    "ARTIFACTS_DIR",
]
