//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use std::collections::HashMap;

use sea_orm::{
    ActiveModelTrait, ActiveValue::Set, ConnectionTrait, DatabaseConnection, DbErr, QueryFilter,
    entity::prelude::*,
};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "app_kv")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub key: String,
    #[sea_orm(column_type = "Text")]
    pub value: String,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}

pub async fn get(connection: &DatabaseConnection, key: &str) -> Result<Option<String>, DbErr> {
    Ok(get_entry(connection, key).await?.map(|row| row.value))
}

pub async fn get_entry(connection: &DatabaseConnection, key: &str) -> Result<Option<Model>, DbErr> {
    Entity::find_by_id(key.to_string()).one(connection).await
}

pub async fn set(connection: &DatabaseConnection, key: &str, value: &str) -> Result<(), DbErr> {
    let _ = set_entry(connection, key, value).await?;
    Ok(())
}

pub async fn set_entry(
    connection: &DatabaseConnection,
    key: &str,
    value: &str,
) -> Result<Model, DbErr> {
    let updated_at = now_utc();
    if let Some(existing) = Entity::find_by_id(key.to_string()).one(connection).await? {
        let mut active_model: ActiveModel = existing.into();
        active_model.value = Set(value.to_string());
        active_model.updated_at = Set(updated_at);
        active_model.update(connection).await
    } else {
        ActiveModel {
            key: Set(key.to_string()),
            value: Set(value.to_string()),
            updated_at: Set(updated_at),
        }
        .insert(connection)
        .await
    }
}

pub async fn delete<C: ConnectionTrait>(connection: &C, key: &str) -> Result<(), DbErr> {
    Entity::delete_by_id(key.to_string())
        .exec(connection)
        .await
        .map(|_| ())
}

pub async fn get_many(
    connection: &DatabaseConnection,
    keys: &[&str],
) -> Result<HashMap<String, String>, DbErr> {
    if keys.is_empty() {
        return Ok(HashMap::new());
    }

    let rows = Entity::find()
        .filter(Column::Key.is_in(keys.iter().map(|key| (*key).to_string())))
        .all(connection)
        .await?;

    let mut values = HashMap::with_capacity(rows.len());
    for row in rows {
        values.insert(row.key, row.value);
    }

    Ok(values)
}

pub async fn set_entry_with_updated_at<C: ConnectionTrait>(
    connection: &C,
    key: &str,
    value: &str,
    updated_at: DateTime,
) -> Result<Model, DbErr> {
    if let Some(existing) = Entity::find_by_id(key.to_string()).one(connection).await? {
        let mut active_model: ActiveModel = existing.into();
        active_model.value = Set(value.to_string());
        active_model.updated_at = Set(updated_at);
        active_model.update(connection).await
    } else {
        ActiveModel {
            key: Set(key.to_string()),
            value: Set(value.to_string()),
            updated_at: Set(updated_at),
        }
        .insert(connection)
        .await
    }
}

fn now_utc() -> DateTime {
    DateTimeUtc::from(std::time::SystemTime::now()).naive_utc()
}
