//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(
    Clone,
    Debug,
    PartialEq,
    Eq,
    Hash,
    EnumIter,
    DeriveActiveEnum,
    serde::Serialize,
    serde::Deserialize,
)]
#[sea_orm(rs_type = "String", db_type = "String(StringLen::None)")]
pub enum HyperlinkArtifactKind {
    #[sea_orm(string_value = "snapshot_warc")]
    SnapshotWarc,
    #[sea_orm(string_value = "pdf_source")]
    PdfSource,
    #[sea_orm(string_value = "snapshot_error")]
    SnapshotError,
    #[sea_orm(string_value = "readable_text")]
    ReadableText,
    #[sea_orm(string_value = "readable_meta")]
    ReadableMeta,
    #[sea_orm(string_value = "readable_error")]
    ReadableError,
    #[sea_orm(string_value = "screenshot_png")]
    ScreenshotPng,
    #[sea_orm(string_value = "screenshot_thumb_png")]
    ScreenshotThumbPng,
    #[sea_orm(string_value = "screenshot_dark_png")]
    ScreenshotDarkPng,
    #[sea_orm(string_value = "screenshot_thumb_dark_png")]
    ScreenshotThumbDarkPng,
    #[sea_orm(string_value = "screenshot_error")]
    ScreenshotError,
}

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "hyperlink_artifact")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub hyperlink_id: i32,
    pub job_id: Option<i32>,
    pub kind: HyperlinkArtifactKind,
    pub payload: Vec<u8>,
    pub storage_path: Option<String>,
    pub storage_backend: Option<String>,
    pub checksum_sha256: Option<String>,
    pub content_type: String,
    pub size_bytes: i32,
    pub created_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::hyperlink::Entity",
        from = "Column::HyperlinkId",
        to = "super::hyperlink::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Hyperlink,
    #[sea_orm(
        belongs_to = "super::hyperlink_processing_job::Entity",
        from = "Column::JobId",
        to = "super::hyperlink_processing_job::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    HyperlinkProcessingJob,
}

impl Related<super::hyperlink::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Hyperlink.def()
    }
}

impl Related<super::hyperlink_processing_job::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::HyperlinkProcessingJob.def()
    }
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {
    #[sea_orm(entity = "super::hyperlink::Entity")]
    Hyperlink,
    #[sea_orm(entity = "super::hyperlink_processing_job::Entity")]
    HyperlinkProcessingJob,
}

impl ActiveModelBehavior for ActiveModel {}
