//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "hyperlink")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub title: String,
    pub url: String,
    pub raw_url: String,
    pub discovery_depth: i32,
    pub clicks_count: i32,
    pub last_clicked_at: Option<DateTime>,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::hyperlink_processing_job::Entity")]
    HyperlinkProcessingJob,
    #[sea_orm(has_many = "super::hyperlink_artifact::Entity")]
    HyperlinkArtifact,
}

impl Related<super::hyperlink_processing_job::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::HyperlinkProcessingJob.def()
    }
}

impl Related<super::hyperlink_artifact::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::HyperlinkArtifact.def()
    }
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {
    #[sea_orm(entity = "super::hyperlink_processing_job::Entity")]
    HyperlinkProcessingJob,
    #[sea_orm(entity = "super::hyperlink_artifact::Entity")]
    HyperlinkArtifact,
}

impl ActiveModelBehavior for ActiveModel {}
