//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "hyperlink_search_fts")]
pub struct Model {
    #[sea_orm(ignore, column_type = "custom(\"\")", select_as = "text", nullable)]
    pub title: Option<String>,
    #[sea_orm(ignore, column_type = "custom(\"\")", select_as = "text", nullable)]
    pub url: Option<String>,
    #[sea_orm(ignore, column_type = "custom(\"\")", select_as = "text", nullable)]
    pub readable_text: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
