//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(
    Clone, Debug, PartialEq, Eq, EnumIter, DeriveActiveEnum, serde::Serialize, serde::Deserialize,
)]
#[sea_orm(rs_type = "String", db_type = "String(StringLen::None)")]
pub enum HyperlinkProcessingJobState {
    #[sea_orm(string_value = "queued")]
    Queued,
    #[sea_orm(string_value = "running")]
    Running,
    #[sea_orm(string_value = "succeeded")]
    Succeeded,
    #[sea_orm(string_value = "failed")]
    Failed,
}

#[derive(
    Clone, Debug, PartialEq, Eq, EnumIter, DeriveActiveEnum, serde::Serialize, serde::Deserialize,
)]
#[sea_orm(rs_type = "String", db_type = "String(StringLen::None)")]
pub enum HyperlinkProcessingJobKind {
    #[sea_orm(string_value = "snapshot")]
    Snapshot,
    #[sea_orm(string_value = "og")]
    Og,
    #[sea_orm(string_value = "oembed")]
    Oembed,
    #[sea_orm(string_value = "readability")]
    Readability,
    #[sea_orm(string_value = "sublink_discovery")]
    SublinkDiscovery,
}

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "hyperlink_processing_job")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(indexed)]
    pub hyperlink_id: i32,
    #[sea_orm(indexed)]
    #[sea_orm(default_value = "snapshot")]
    pub kind: HyperlinkProcessingJobKind,
    #[sea_orm(indexed)]
    pub state: HyperlinkProcessingJobState,
    pub error_message: Option<String>,
    pub queued_at: DateTime,
    pub started_at: Option<DateTime>,
    pub finished_at: Option<DateTime>,
    #[sea_orm(indexed)]
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::hyperlink::Entity",
        from = "Column::HyperlinkId",
        to = "super::hyperlink::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Hyperlink,
    #[sea_orm(has_many = "super::hyperlink_artifact::Entity")]
    HyperlinkArtifact,
    #[sea_orm(has_many = "super::llm_interaction::Entity")]
    LlmInteraction,
}

impl Related<super::hyperlink::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Hyperlink.def()
    }
}

impl Related<super::hyperlink_artifact::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::HyperlinkArtifact.def()
    }
}

impl Related<super::llm_interaction::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LlmInteraction.def()
    }
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {
    #[sea_orm(entity = "super::hyperlink::Entity")]
    Hyperlink,
    #[sea_orm(entity = "super::hyperlink_artifact::Entity")]
    HyperlinkArtifact,
}

impl ActiveModelBehavior for ActiveModel {}
