//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(
    Clone, Debug, PartialEq, Eq, EnumIter, DeriveActiveEnum, serde::Serialize, serde::Deserialize,
)]
#[sea_orm(rs_type = "String", db_type = "String(StringLen::None)")]
pub enum HyperlinkProcessingState {
    #[sea_orm(string_value = "waiting")]
    Waiting,
    #[sea_orm(string_value = "processing")]
    Processing,
    #[sea_orm(string_value = "processed")]
    Processed,
    #[sea_orm(string_value = "error")]
    Error,
}

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "hyperlink")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub title: String,
    pub url: String,
    pub clicks_count: i32,
    pub last_clicked_at: Option<DateTime>,
    pub processing_state: HyperlinkProcessingState,
    pub processing_started_at: Option<DateTime>,
    pub processed_at: Option<DateTime>,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::hyperlink_processing_error::Entity")]
    HyperlinkProcessingError,
}

impl Related<super::hyperlink_processing_error::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::HyperlinkProcessingError.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
