//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "hyperlink_relation")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub parent_hyperlink_id: i32,
    pub child_hyperlink_id: i32,
    pub created_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::hyperlink::Entity",
        from = "Column::ParentHyperlinkId",
        to = "super::hyperlink::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    ParentHyperlink,
    #[sea_orm(
        belongs_to = "super::hyperlink::Entity",
        from = "Column::ChildHyperlinkId",
        to = "super::hyperlink::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    ChildHyperlink,
}

impl ActiveModelBehavior for ActiveModel {}
