//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::{
    ActiveModelTrait, ActiveValue::Set, ColumnTrait, ConnectionTrait, DatabaseConnection,
    EntityTrait, ExprTrait, QueryFilter, QueryOrder, QuerySelect, TransactionTrait,
    entity::prelude::*, sea_query::Expr,
};

pub const ROOT_DISCOVERY_DEPTH: i32 = 0;
pub const DISCOVERED_DISCOVERY_DEPTH: i32 = 1;

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "String(StringLen::N(16))")]
pub enum HyperlinkSourceType {
    #[sea_orm(string_value = "unknown")]
    Unknown,
    #[sea_orm(string_value = "html")]
    Html,
    #[sea_orm(string_value = "pdf")]
    Pdf,
}

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "hyperlink")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub title: String,
    #[sea_orm(unique, indexed)]
    pub url: String,
    #[sea_orm(indexed, default_value = "")]
    pub raw_url: String,
    pub summary: Option<String>,
    pub og_title: Option<String>,
    pub og_description: Option<String>,
    pub og_type: Option<String>,
    pub og_url: Option<String>,
    pub og_image_url: Option<String>,
    pub og_site_name: Option<String>,
    #[sea_orm(indexed, default_value = 0)]
    pub discovery_depth: i32,
    #[sea_orm(indexed, default_value = 0)]
    pub clicks_count: i32,
    #[sea_orm(indexed)]
    pub last_clicked_at: Option<DateTime>,
    #[sea_orm(default_value = "unknown")]
    pub source_type: HyperlinkSourceType,
    #[sea_orm(indexed)]
    pub rss_feed_id: Option<i32>,
    #[sea_orm(indexed)]
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::hyperlink_artifact::Entity")]
    HyperlinkArtifact,
    #[sea_orm(has_many = "super::hyperlink_processing_job::Entity")]
    HyperlinkProcessingJob,
    #[sea_orm(has_one = "super::hyperlink_search_doc::Entity")]
    HyperlinkSearchDoc,
    #[sea_orm(has_many = "super::llm_interaction::Entity")]
    LlmInteraction,
    #[sea_orm(
        belongs_to = "super::rss_feed::Entity",
        from = "Column::RssFeedId",
        to = "super::rss_feed::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    RssFeed,
}

impl Related<super::hyperlink_processing_job::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::HyperlinkProcessingJob.def()
    }
}

impl Related<super::hyperlink_artifact::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::HyperlinkArtifact.def()
    }
}

impl Related<super::hyperlink_search_doc::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::HyperlinkSearchDoc.def()
    }
}

impl Related<super::llm_interaction::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LlmInteraction.def()
    }
}

impl Related<super::rss_feed::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RssFeed.def()
    }
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {
    #[sea_orm(entity = "super::hyperlink_processing_job::Entity")]
    HyperlinkProcessingJob,
    #[sea_orm(entity = "super::hyperlink_artifact::Entity")]
    HyperlinkArtifact,
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Clone, Debug, Default)]
pub struct TitleBackfillReport {
    pub scanned: usize,
    pub updated: usize,
    pub unchanged: usize,
}

pub async fn find_by_url(
    connection: &DatabaseConnection,
    url: &str,
) -> Result<Option<Model>, DbErr> {
    Entity::find()
        .filter(Column::Url.eq(url.to_string()))
        .order_by_asc(Column::Id)
        .one(connection)
        .await
}

pub async fn list_updated_after(
    connection: &impl ConnectionTrait,
    updated_after: DateTime,
) -> Result<Vec<Model>, DbErr> {
    Entity::find()
        .filter(Column::UpdatedAt.gt(updated_after))
        .order_by_asc(Column::UpdatedAt)
        .order_by_asc(Column::Id)
        .all(connection)
        .await
}

pub async fn increment_click_count_by_id(
    connection: &DatabaseConnection,
    id: i32,
) -> Result<Option<Model>, DbErr> {
    let now = now_utc();
    let updated = Entity::update_many()
        .col_expr(Column::ClicksCount, Expr::col(Column::ClicksCount).add(1))
        .col_expr(Column::LastClickedAt, Expr::val(now).into())
        .filter(Column::Id.eq(id))
        .exec(connection)
        .await?;

    if updated.rows_affected == 0 {
        return Ok(None);
    }

    Entity::find_by_id(id).one(connection).await
}

pub async fn delete_by_id_with_tombstone(
    connection: &DatabaseConnection,
    id: i32,
) -> Result<bool, DbErr> {
    if Entity::find_by_id(id).one(connection).await?.is_none() {
        return Ok(false);
    }

    let deleted_at = now_utc();
    let txn = connection.begin().await?;
    super::hyperlink_tombstone::upsert(&txn, id, deleted_at).await?;
    crate::app::models::readability_progress::delete(&txn, id).await?;
    let deleted = Entity::delete_by_id(id).exec(&txn).await?;

    if deleted.rows_affected == 0 {
        txn.rollback().await?;
        return Ok(false);
    }

    txn.commit().await?;
    Ok(true)
}

pub async fn backfill_clean_titles(
    connection: &DatabaseConnection,
    batch_size: u64,
) -> Result<TitleBackfillReport, DbErr> {
    let mut report = TitleBackfillReport::default();
    let mut last_id = 0i32;
    let batch_size = batch_size.clamp(1, 10_000);

    loop {
        let rows = Entity::find()
            .filter(Column::Id.gt(last_id))
            .order_by_asc(Column::Id)
            .limit(batch_size)
            .all(connection)
            .await?;

        if rows.is_empty() {
            break;
        }

        for row in rows {
            last_id = row.id;
            report.scanned += 1;

            let cleaned_title = crate::app::models::hyperlink_title::strip_site_affixes(
                row.title.as_str(),
                row.url.as_str(),
                row.raw_url.as_str(),
            );
            if cleaned_title == row.title {
                report.unchanged += 1;
                continue;
            }

            let mut active_model: ActiveModel = row.into();
            active_model.title = Set(cleaned_title);
            active_model.updated_at = Set(now_utc());
            active_model.update(connection).await?;
            report.updated += 1;
        }
    }

    Ok(report)
}

fn now_utc() -> DateTime {
    DateTimeUtc::from(std::time::SystemTime::now()).naive_utc()
}
