//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::{
    ActiveModelTrait, ActiveValue::Set, ConnectionTrait, QueryFilter, QueryOrder,
    entity::prelude::*,
};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "hyperlink_tombstone")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub hyperlink_id: i32,
    #[sea_orm(indexed)]
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}

pub async fn upsert<C: ConnectionTrait>(
    connection: &C,
    hyperlink_id: i32,
    updated_at: DateTime,
) -> Result<(), DbErr> {
    if let Some(existing) = Entity::find_by_id(hyperlink_id).one(connection).await? {
        let mut active: ActiveModel = existing.into();
        active.updated_at = Set(updated_at);
        active.update(connection).await?;
    } else {
        ActiveModel {
            hyperlink_id: Set(hyperlink_id),
            updated_at: Set(updated_at),
        }
        .insert(connection)
        .await?;
    }

    Ok(())
}

pub async fn list_updated_after(
    connection: &impl ConnectionTrait,
    updated_after: DateTime,
) -> Result<Vec<Model>, DbErr> {
    Entity::find()
        .filter(Column::UpdatedAt.gt(updated_after))
        .order_by_asc(Column::UpdatedAt)
        .order_by_asc(Column::HyperlinkId)
        .all(connection)
        .await
}
