//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use std::collections::HashMap;

use sea_orm::{
    ActiveModelTrait, ActiveValue::Set, ConnectionTrait, DatabaseConnection, DbBackend,
    QueryFilter, QueryOrder, QuerySelect, Statement, entity::prelude::*,
};

#[derive(
    Clone, Debug, PartialEq, Eq, EnumIter, DeriveActiveEnum, serde::Serialize, serde::Deserialize,
)]
#[sea_orm(rs_type = "String", db_type = "String(StringLen::None)")]
pub enum HyperlinkProcessingJobState {
    #[sea_orm(string_value = "queued")]
    Queued,
    #[sea_orm(string_value = "running")]
    Running,
    #[sea_orm(string_value = "succeeded")]
    Succeeded,
    #[sea_orm(string_value = "failed")]
    Failed,
}

impl HyperlinkProcessingJobState {
    pub fn as_str(&self) -> &'static str {
        match self {
            Self::Queued => "queued",
            Self::Running => "running",
            Self::Succeeded => "succeeded",
            Self::Failed => "failed",
        }
    }
}

#[derive(
    Clone, Debug, PartialEq, Eq, EnumIter, DeriveActiveEnum, serde::Serialize, serde::Deserialize,
)]
#[sea_orm(rs_type = "String", db_type = "String(StringLen::None)")]
pub enum HyperlinkProcessingJobKind {
    #[sea_orm(string_value = "snapshot")]
    Snapshot,
    #[sea_orm(string_value = "og")]
    Og,
    #[sea_orm(string_value = "oembed")]
    Oembed,
    #[sea_orm(string_value = "readability")]
    Readability,
    #[sea_orm(string_value = "sublink_discovery")]
    SublinkDiscovery,
}

impl HyperlinkProcessingJobKind {
    pub fn as_str(&self) -> &'static str {
        match self {
            Self::Snapshot => "snapshot",
            Self::Og => "og",
            Self::Oembed => "oembed",
            Self::Readability => "readability",
            Self::SublinkDiscovery => "sublink_discovery",
        }
    }
}

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "hyperlink_processing_job")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(indexed)]
    pub hyperlink_id: i32,
    #[sea_orm(indexed)]
    #[sea_orm(default_value = "snapshot")]
    pub kind: HyperlinkProcessingJobKind,
    #[sea_orm(indexed)]
    pub state: HyperlinkProcessingJobState,
    pub error_message: Option<String>,
    pub queued_at: DateTime,
    pub started_at: Option<DateTime>,
    pub finished_at: Option<DateTime>,
    #[sea_orm(indexed)]
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::hyperlink::Entity",
        from = "Column::HyperlinkId",
        to = "super::hyperlink::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Hyperlink,
    #[sea_orm(has_many = "super::hyperlink_artifact::Entity")]
    HyperlinkArtifact,
    #[sea_orm(has_many = "super::llm_interaction::Entity")]
    LlmInteraction,
}

impl Related<super::hyperlink::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Hyperlink.def()
    }
}

impl Related<super::hyperlink_artifact::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::HyperlinkArtifact.def()
    }
}

impl Related<super::llm_interaction::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LlmInteraction.def()
    }
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {
    #[sea_orm(entity = "super::hyperlink::Entity")]
    Hyperlink,
    #[sea_orm(entity = "super::hyperlink_artifact::Entity")]
    HyperlinkArtifact,
}

impl ActiveModelBehavior for ActiveModel {}

pub type ProcessingQueueSender = crate::queue::ProcessingQueue;
const ACTIVE_JOB_UNIQUE_INDEX_NAME: &str = "idx_hyperlink_processing_job_active_unique";

pub async fn enqueue_for_hyperlink(
    connection: &DatabaseConnection,
    hyperlink_id: i32,
    processing_queue: Option<&ProcessingQueueSender>,
) -> Result<Model, DbErr> {
    enqueue_for_hyperlink_kind(
        connection,
        hyperlink_id,
        HyperlinkProcessingJobKind::Snapshot,
        processing_queue,
    )
    .await
}

pub async fn enqueue_for_hyperlink_kind(
    connection: &DatabaseConnection,
    hyperlink_id: i32,
    kind: HyperlinkProcessingJobKind,
    processing_queue: Option<&ProcessingQueueSender>,
) -> Result<Model, DbErr> {
    let now = now_utc();
    let model = match (ActiveModel {
        hyperlink_id: Set(hyperlink_id),
        kind: Set(kind.clone()),
        state: Set(HyperlinkProcessingJobState::Queued),
        error_message: Set(None),
        queued_at: Set(now),
        started_at: Set(None),
        finished_at: Set(None),
        created_at: Set(now),
        updated_at: Set(now),
        ..Default::default()
    })
    .insert(connection)
    .await
    {
        Ok(model) => model,
        Err(error) if is_active_job_unique_violation(&error) => {
            if let Some(existing) =
                active_for_hyperlink_kind(connection, hyperlink_id, kind).await?
            {
                return Ok(existing);
            }
            return Err(error);
        }
        Err(error) => return Err(error),
    };

    if let Some(queue) = processing_queue {
        if let Err(error) = queue.enqueue_processing_job(model.id).await {
            if let Err(cleanup_error) = Entity::delete_by_id(model.id).exec(connection).await {
                tracing::error!(
                    hyperlink_id,
                    job_id = model.id,
                    enqueue_error = %error,
                    cleanup_error = %cleanup_error,
                    "failed to enqueue hyperlink processing job and failed to clean up queued row"
                );
            }
            return Err(DbErr::Custom(
                format!(
                    "failed to enqueue hyperlink processing job {}: {error}",
                    model.id
                )
                .into(),
            ));
        }
    }

    Ok(model)
}

async fn active_for_hyperlink_kind(
    connection: &DatabaseConnection,
    hyperlink_id: i32,
    kind: HyperlinkProcessingJobKind,
) -> Result<Option<Model>, DbErr> {
    Entity::find()
        .filter(Column::HyperlinkId.eq(hyperlink_id))
        .filter(Column::Kind.eq(kind))
        .filter(Column::State.is_in([
            HyperlinkProcessingJobState::Queued,
            HyperlinkProcessingJobState::Running,
        ]))
        .order_by_desc(Column::CreatedAt)
        .order_by_desc(Column::Id)
        .one(connection)
        .await
}

fn is_active_job_unique_violation(error: &DbErr) -> bool {
    let message = match error {
        DbErr::Exec(exec_error) => exec_error.to_string(),
        DbErr::Query(query_error) => query_error.to_string(),
        _ => return false,
    };

    let normalized = message.to_ascii_lowercase();
    normalized.contains(ACTIVE_JOB_UNIQUE_INDEX_NAME)
        || normalized.contains(
            "unique constraint failed: hyperlink_processing_job.hyperlink_id, hyperlink_processing_job.kind",
        )
}

pub async fn latest_for_hyperlink(
    connection: &DatabaseConnection,
    hyperlink_id: i32,
) -> Result<Option<Model>, DbErr> {
    Entity::find()
        .filter(Column::HyperlinkId.eq(hyperlink_id))
        .filter(Column::Kind.is_in(supported_kinds()))
        .order_by_desc(Column::CreatedAt)
        .order_by_desc(Column::Id)
        .one(connection)
        .await
}

pub async fn latest_for_hyperlinks(
    connection: &DatabaseConnection,
    hyperlink_ids: &[i32],
) -> Result<HashMap<i32, Model>, DbErr> {
    if hyperlink_ids.is_empty() {
        return Ok(HashMap::new());
    }

    let jobs = Entity::find()
        .filter(Column::HyperlinkId.is_in(hyperlink_ids.to_vec()))
        .filter(Column::Kind.is_in(supported_kinds()))
        .order_by_desc(Column::CreatedAt)
        .order_by_desc(Column::Id)
        .all(connection)
        .await?;

    let mut latest = HashMap::with_capacity(hyperlink_ids.len());
    for job in jobs {
        latest.entry(job.hyperlink_id).or_insert(job);
    }

    Ok(latest)
}

pub async fn recent_for_hyperlink(
    connection: &DatabaseConnection,
    hyperlink_id: i32,
    limit: u64,
) -> Result<Vec<Model>, DbErr> {
    Entity::find()
        .filter(Column::HyperlinkId.eq(hyperlink_id))
        .filter(Column::Kind.is_in(supported_kinds()))
        .order_by_desc(Column::CreatedAt)
        .order_by_desc(Column::Id)
        .limit(limit)
        .all(connection)
        .await
}

fn processing_task_job_type() -> &'static str {
    std::any::type_name::<crate::queue::ProcessingTask>()
}

fn supported_kinds() -> [HyperlinkProcessingJobKind; 5] {
    [
        HyperlinkProcessingJobKind::Snapshot,
        HyperlinkProcessingJobKind::Og,
        HyperlinkProcessingJobKind::Oembed,
        HyperlinkProcessingJobKind::Readability,
        HyperlinkProcessingJobKind::SublinkDiscovery,
    ]
}

pub async fn delete_stale_active_rows(connection: &DatabaseConnection) -> Result<u64, DbErr> {
    let statement = Statement::from_sql_and_values(
        DbBackend::Sqlite,
        "DELETE FROM hyperlink_processing_job
         WHERE state IN ('queued', 'running')
           AND NOT EXISTS (
               SELECT 1
               FROM jobs queue_job
               WHERE queue_job.job_type = ?
                 AND queue_job.status IN ('queued', 'processing')
                 AND json_valid(queue_job.payload)
                 AND CAST(json_extract(queue_job.payload, '$.processing_job_id') AS INTEGER) = hyperlink_processing_job.id
           )"
            .to_string(),
        vec![processing_task_job_type().into()],
    );

    Ok(connection.execute_raw(statement).await?.rows_affected())
}

fn now_utc() -> DateTime {
    DateTimeUtc::from(std::time::SystemTime::now()).naive_utc()
}

#[cfg(test)]
#[path = "../../tests/unit/app_models_hyperlink_processing_job.rs"]
mod tests;
