//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "hyperlink_search_fts_idx")]
pub struct Model {
    #[sea_orm(
        primary_key,
        auto_increment = false,
        ignore,
        column_type = "custom(\"\")",
        select_as = "text"
    )]
    pub segid: String,
    #[sea_orm(
        primary_key,
        auto_increment = false,
        ignore,
        column_type = "custom(\"\")",
        select_as = "text"
    )]
    pub term: String,
    #[sea_orm(ignore, column_type = "custom(\"\")", select_as = "text", nullable)]
    pub pgno: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
