//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "job_events")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub job_id: i64,
    #[sea_orm(column_type = "Text")]
    pub event_type: String,
    pub at_epoch_s: i64,
    pub attempt: Option<i64>,
    #[sea_orm(column_type = "Text", nullable)]
    pub error: Option<String>,
    pub queued_ms: Option<i64>,
    pub processing_ms: Option<i64>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
