//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

pub mod prelude;

pub mod hyperlink;
pub mod hyperlink_artifact;
pub mod hyperlink_processing_job;
pub mod hyperlink_relation;
pub mod hyperlink_tombstone;
