//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(
    Clone, Debug, PartialEq, Eq, EnumIter, DeriveActiveEnum, serde::Serialize, serde::Deserialize,
)]
#[sea_orm(rs_type = "String", db_type = "String(StringLen::None)")]
pub enum TagState {
    #[sea_orm(string_value = "USER")]
    User,
    #[sea_orm(string_value = "AI_APPROVED")]
    AiApproved,
    #[sea_orm(string_value = "AI_PENDING")]
    AiPending,
    #[sea_orm(string_value = "AI_REJECTED")]
    AiRejected,
}

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "tag")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    pub name_key: String,
    #[sea_orm(default_value = "AI_PENDING")]
    pub state: TagState,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::hyperlink_tag::Entity")]
    HyperlinkTag,
}

impl Related<super::hyperlink_tag::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::HyperlinkTag.def()
    }
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {
    #[sea_orm(entity = "super::hyperlink_tag::Entity")]
    HyperlinkTag,
}

impl ActiveModelBehavior for ActiveModel {}
