//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "taxonomy_cleanup_cluster")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub run_id: i64,
    pub kind: String,
    pub cluster_key: String,
    pub cluster_label: String,
    pub sort_index: i64,
    pub status: String,
    pub tag_count: i64,
    pub usage_count: i64,
    pub attempt_count: i64,
    #[sea_orm(column_type = "Text")]
    pub input_snapshot_json: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub proposal_json: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub error_message: Option<String>,
    pub started_at: Option<DateTime>,
    pub finished_at: Option<DateTime>,
    pub applied_at: Option<DateTime>,
    pub discarded_at: Option<DateTime>,
    pub stale_at: Option<DateTime>,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::taxonomy_cleanup_run::Entity",
        from = "Column::RunId",
        to = "super::taxonomy_cleanup_run::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    TaxonomyCleanupRun,
}

impl Related<super::taxonomy_cleanup_run::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TaxonomyCleanupRun.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
