//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "taxonomy_cleanup_run")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub status: String,
    pub provider: String,
    pub model: String,
    pub prompt_version: String,
    pub kind_coverage: String,
    #[sea_orm(column_type = "Text")]
    pub snapshot_json: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub final_merge_json: Option<String>,
    pub total_clusters: i64,
    pub completed_clusters: i64,
    pub ready_clusters: i64,
    pub failed_clusters: i64,
    pub stale_clusters: i64,
    pub applied_clusters: i64,
    pub discarded_clusters: i64,
    pub unresolved_conflicts: i64,
    #[sea_orm(column_type = "Text", nullable)]
    pub error_message: Option<String>,
    pub started_at: DateTime,
    pub finished_at: Option<DateTime>,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::taxonomy_cleanup_cluster::Entity")]
    TaxonomyCleanupCluster,
}

impl Related<super::taxonomy_cleanup_cluster::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TaxonomyCleanupCluster.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
